baseURL = "https://shelbybachman.github.io/"
publishDir = "shelbybachman.github.io"
languageCode = "en-us"
title = "Shelby Bachman"
theme = "cactus"
copyright = "Shelby Bachman" # cactus will use title if copyright is not set
# disqusShortname = "" # Used when comments is enabled. Cactus will use site title if not set
# googleAnalytics = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]

# summaryLength = 2

# Main menu which appears below site header.
[[menu.main]]
name = "about"
url = "/about"
weight = 1

[[menu.main]]
name = "portfolio"
url = "/portfolio"
weight = 2

[[menu.main]]
name = "cv"
url = "https://shelbybachman.github.io/cv/"
weight = 3

#[[menu.main]]
#name = "blog"
#url = "/posts"
#weight = 3

#[[menu.main]]
#name = "tags"
#url = "/tags"
#weight = 4

[markup]
  [markup.tableOfContents]
    endLevel = 4
    ordered = false
    startLevel = 2
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]

  colortheme = "white" # dark, light, white, or classic
  rss = false # generate rss feed. default value is false
  googleAnalyticsAsync = false # use asynchronous tracking. Synchronous tracking by default

  # Home page settings
  description = "PhD Student | University of Southern California"
  mainSection = "posts" # your main section
  showAllPostsOnHomePage = false # default
  postsOnHomePage = 0 # this option will be ignored if showAllPostsOnHomePage is set to true
  tagsOverview = false # show tags overview by default.
  showProjectsList = false # show projects list by default (if projects data file exists).
  projectsUrl = "https://www.github.com/shelbybachman" # title link for projects list

  # https://gohugo.io/functions/format/#hugo-date-and-time-templating-reference
  dateFormat = "2006-01-02" # default

  # Post page settings
  show_updated = false # default

  [params.comments]
    enabled = false # default
    engine = "disqus" # more supported engines will be added.

  # the value of name should be an valid font awesome icon name (brands type)
  # https://fontawesome.com/icons?d=gallery&s=brands
  [[params.social]]
    name = "github"
    link = "https://github.com/shelbybachman"
  [[params.social]]
    name = "twitter"
    link = "https://www.twitter.com/shelbybachman"
  [[params.social]]
    name = "linkedin"
    link = "https://www.linkedin.com/in/shelby-bachman"
  [[params.social]]
    name = "researchgate"
    link = "https://www.researchgate.net/profile/Shelby_Bachman"
  [[params.social]]
    name = "orcid"
    link = "http://orcid.org/0000-0002-4460-4661"
